- sampling_method: ode
  num_sampling_steps: [64]
  cfgs: [1]
  self_cond_cfg_scales: [3]
  time_schedule: logit_normal

- sampling_method: heun
  num_sampling_steps: [32]
  cfgs: [1]
  self_cond_cfg_scales: [3]
  time_schedule: logit_normal

- sampling_method: dpm_solver_2_like
  num_sampling_steps: [32]
  cfgs: [1]
  self_cond_cfg_scales: [3]
  time_schedule: logit_normal
